name: website

on:
  pull_request:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash -l {0}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Build the documentation and check links
        run: make html -b linkcheck

      - name: Deploy to gh-pages
        run: |
          # Configure git to be the GitHub Actions account
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          # Deploy
          make deploy
